/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AutoreSchema extends BaseModel {
  static $columns = ['avatar', 'bio', 'createdAt', 'email', 'id', 'nombre', 'redes', 'rol', 'updatedAt'] as const
  $columns = AutoreSchema.$columns
  @column()
  declare avatar: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column()
  declare redes: string | null
  @column()
  declare rol: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategoriaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nombre', 'slug', 'updatedAt'] as const
  $columns = CategoriaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComentarioSchema extends BaseModel {
  static $columns = ['autorEmail', 'autorNombre', 'creadoEn', 'cuerpo', 'estado', 'id', 'padreId', 'postId'] as const
  $columns = ComentarioSchema.$columns
  @column()
  declare autorEmail: string
  @column()
  declare autorNombre: string
  @column.dateTime()
  declare creadoEn: DateTime | null
  @column()
  declare cuerpo: string
  @column()
  declare estado: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare padreId: number | null
  @column()
  declare postId: number
}

export class EtiquetaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nombre', 'slug', 'updatedAt'] as const
  $columns = EtiquetaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostSchema extends BaseModel {
  static $columns = ['autorEmail', 'autorId', 'autorNombre', 'categoriaId', 'categoriaNombre', 'createdAt', 'cuerpo', 'estado', 'etiquetas', 'id', 'imagenPortada', 'publicadoEn', 'resumen', 'slug', 'titulo', 'updatedAt'] as const
  $columns = PostSchema.$columns
  @column()
  declare autorEmail: string | null
  @column()
  declare autorId: number | null
  @column()
  declare autorNombre: string | null
  @column()
  declare categoriaId: number | null
  @column()
  declare categoriaNombre: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cuerpo: string | null
  @column()
  declare estado: string
  @column()
  declare etiquetas: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagenPortada: string | null
  @column.dateTime()
  declare publicadoEn: DateTime | null
  @column()
  declare resumen: string | null
  @column()
  declare slug: string
  @column()
  declare titulo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
