/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ComentarioTransformer from '#transformers/comentario_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Comentario = InferData<ComentarioTransformer>
  export namespace Comentario {
    export type Variants = InferVariants<ComentarioTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
